<?
/*
 * page_AccountList.php
 *
 * This template frames the display of the Account List page.
 *
 * Required Template Variables:
 *  $pageLabels :   The values of the labels to display on the page.
 *  $pageContent :  The Account List generated by the siteDataList
 */
 
// First load the common Template Tools object
// This object handles the common display of our form items and
// text formmatting tools.
$fileName = 'objects/TemplateTools.php';
$path = Page::findPathExtension( $fileName );
require_once( $path.$fileName);

$templateTools = new TemplateTools();


// load the page labels
$templateTools->loadPageLabels( $pageLabels );

?>
<p><span class="heading"><? echo $templateTools->getPageLabel('[Title]'); ?></span></p>
<p><span class="text"><? echo $templateTools->getPageLabel('[Instr]'); ?></span></p>
<p><span class="text"><? echo $templateTools->getPageLabel('[ChooseGroup]'); ?></span> <? 

// create JumpList
$templateTools->showJumpListByArray( 'accountGroup', $accountGroup, $jumpList);

?></p>
<? 

echo $pageContent;
    
    
?>
