<?php
/**
 * @package cim_hrdb
 */ 
/**
 * class page_PersonInfo 
 * <pre> 
 * Displays the info for a given person.
 * </pre>
 * @author CIM Team
 * Date:   06 Apr 2006
 */
 // RAD Tools: DataSingle Page
class  page_PersonInfo extends PageDisplay_DisplaySingle {

	//CONSTANTS:
    
    /** The list of fields to be displayed */
    const DISPLAY_FIELDS = 'person_fname,person_lname,person_phone,person_email,person_addr,person_city,province_id,person_pc,gender_id';
    
    /** The Multilingual Page Key for labels on this page */
    const MULTILINGUAL_PAGE_KEY = 'page_PersonInfo';
    

	//VARIABLES:
	
	/** @var [OBJECT] The viewer object. */
	protected $viewer;
	
    /** @var [STRING] The path to this module's root directory. */
	protected $pathModuleRoot;
	
	/** @var [INTEGER] The initialization value for the itemManager. */
	protected $itemID;



	//CLASS CONSTRUCTOR
	//************************************************************************
	/**
	 * function __construct
	 * <pre>
	 * Initialize the object.
	 * </pre>
	 * @param $pathModuleRoot [STRING] The path to the module's root dir.
	 * @param $viewer [OBJECT] The viewer object.
     * @param $You Did not select a primary key for this DAObj [INTEGER] Initialization value for the itemManager.
	 * @return [void]
	 */
    function __construct($pathModuleRoot, $viewer, $personID )
    {
    
        parent::__construct( page_PersonInfo::DISPLAY_FIELDS );
        
        // initialzie the object values
        $this->pathModuleRoot = $pathModuleRoot;
        $this->viewer = $viewer;

        $this->itemID = $personID;


        // create the item Manager to display
        $this->itemManager = new RowManager_PersonManager( $personID );

        // now initialize the labels for this page
        // start by loading the default field labels for this Module
        $languageID = $viewer->getLanguageID();
        $seriesKey = modulecim_hrdb::MULTILINGUAL_SERIES_KEY;
        $pageKey = modulecim_hrdb::MULTILINGUAL_PAGE_FIELDS;
        $this->labels = new MultilingualManager( $languageID, $seriesKey, $pageKey );
        
        // then load the page specific labels for this page
        $pageKey = page_PersonInfo::MULTILINGUAL_PAGE_KEY;
        $this->labels->loadPageLabels( $pageKey );
         
    }



	//CLASS FUNCTIONS:
	//************************************************************************
	/**
	 * function classMethod
	 * <pre>
	 * [classFunction Description]
	 * </pre>
	 * <pre><code>
	 * [Put PseudoCode Here]
	 * </code></pre>
	 * @param $param1 [$param1 type][optional description of $param1]
	 * @param $param2 [$param2 type][optional description of $param2]
	 * @return [returnValue, can be void]
	 */
    function classMethod($param1, $param2) 
    {
        // CODE
    }	
    
    
    
    //************************************************************************
	/**
	 * function getHTML
	 * <pre>
	 * This method returns the HTML data generated by this object.
	 * </pre>
	 * @return [STRING] HTML Display data.
	 */
    function getHTML() 
    {

        // Uncomment the following line if you want to create a template 
        // tailored for this page:
        //$path = $this->pathModuleRoot.'templates/';
        // Otherwise use the standard Templates for the site:
        $path = SITE_PATH_TEMPLATES;


        /*
         * Update any label tags ...
         */
        // example:
            // $name = $user->getName();
            // $this->labels->setLabelTag( '[Title]', '[userName]', $name);
		  $this->linkLabels[ 'cont' ] = $this->labels->getLabel( '[Continue]');

        // NOTE:  this parent method prepares the $this->template with the 
        // common Display data.  
        $this->prepareTemplate($path);
        
        // for displaying the province properly
        $provinceManager = new RowManager_ProvinceManager( );
        $provinceList = $provinceManager->getListIterator( );
        $provinceArray = $provinceList->getDropListArray( );
        $this->template->set( 'list_province_id', $provinceArray );
        // echo '<pre>'.print_r($provinceArray,true).'</pre>';
        //Gender list.
        $genderManager = new RowManager_GenderManager( );
        $genderList = $genderManager->getListIterator( );
        $genderArray = $genderList->getDropListArray( );
        $this->template->set( 'list_gender_id', $genderArray );

        // uncomment this line if you are creating a template for this page
		//$templateName = 'page_PersonInfo.php';
		// otherwise use the generic site template
		$templateName = 'siteDataSingle.php';
		
		return $this->template->fetch( $templateName );
        
    }
	
}

?>