<?php
/**
 * @package NSSPayRoll
 */ 
/**
 * class obj_AdminSideBar
 * <pre> 
 * This object manages the display of the side bar.
 * </pre>
 * @author Johnny Hausman
 * Date:   12 April 2005
 */
class  obj_SideBar {

	//CONSTANTS:
	/** The XML root node name for this object */
    const MULTILINGUAL_PAGE_KEY = 'obj_SideBar';

	//VARIABLES:
	
	/** @var [STRING] The path to this module's root directory */
	protected $pathModuleRoot;
	
	/** @var [STRING] The path to the site's root directory */
	protected $pathToRoot;
	
	/** @var [OBJECT] the template object */
	protected $template;
	
	/** @var [OBJECT] the labels object */
	protected $labels;
	
	/** @var [ARRAY] array of links for the sidebar */
	protected $links;

	//CLASS CONSTRUCTOR
	//************************************************************************
	/**
	 * function __construct
	 * <pre>
	 * Initialize the obj_AdminSideBar Object.
	 * </pre>
	 * @param $modulePath [STRING] The path from the root directory to this 
	 * module's root directory.
	 * @param $viewer [OBJECT] The viewer object 
	 * @return [void]
	 */
    function __construct( $modulePath, $viewer ) 
    {
        
        $this->pathModuleRoot = $modulePath;
//        $this->pathToRoot = $rootPath;

        $this->links = array();

        // load any labels assigned to this page
        $languageID = $viewer->getLanguageID();
        $seriesKey = modulecim_home::MULTILINGUAL_SERIES_KEY;
        $pageKey = obj_SideBar::MULTILINGUAL_PAGE_KEY;
        $this->labels = new MultilingualManager( $languageID, $seriesKey, $pageKey );

    }



	//CLASS FUNCTIONS:
	//************************************************************************
	/**
	 * function classMethod
	 * <pre>
	 * [classFunction Description]
	 * </pre>
	 * <pre><code>
	 * [Put PseudoCode Here]
	 * </code></pre>
	 * @param $param1 [$param1 type][optional description of $param1]
	 * @param $param2 [$param2 type][optional description of $param2]
	 * @return [returnValue, can be void]
	 */
    function classMethod($param1, $param2)
    {
        // CODE
    }



    //************************************************************************
	/**
	 * function getHTML
	 * <pre>
	 * This method returns the HTML data generated by this object.
	 * </pre>
	 * @return [STRING] HTML Display data.
	 */
    function getHTML()
    {
        // Create a new Template Object
        $this->template = new Template( $this->pathModuleRoot.'templates/' );

        // store the page labels
        $this->template->setXML( 'pageLabels', $this->labels->getLabelXML() );

        // store the links for the sidebar
		$this->template->set( 'links',$this->links );

		// return the html from the commong display template
		return $this->template->fetch( 'obj_SideBar.php' );

    }




	//************************************************************************
	/**
	 * function setLinks
	 * <pre>
	 * Stores the values of the links for this sidebar
	 * </pre>
	 * @param $links [ARRAY] Link Values (key=>link, key=>link,...)
	 * @return [void]
	 */
    function setLinks( $links )
    {
        $this->links = $links;
    }

}

?>