<?php
/*
 * Include required files
 */
$pathFile = 'General/gen_Includes.php';
$extension = '';
    
// Attempt to find proper directory from current page to Root ...
$numAttempts = 0;
while ( (!file_exists($extension.$pathFile)) && ( $numAttempts < 5) ) {
    
    $extension = '../'.$extension;
    $numAttempts++; 
}

require ( $extension.$pathFile );

require( 'SeriesManager.php' );



// Need to define values as Global to be used between functions
$seriesArray = '';
$editLink = '';


// now we drive the application by calling the loadData(), processData(), 
// and getHTML() routines
loadData();
processData();
echo getHTML();



//************************************************************************
/** 
 * loadData()
 *
 * Here we load up all the data we need to run this web page.
 */
function loadData() 
{
    global $seriesArray;
    global $editLink;


    // Get a list of all the series entries in the table
    $seriesArray = array();
    $seriesManager = new RowManager_SeriesManager();
        
    // get all the rows in this table
    $list = $seriesManager->getListIterator();
    
    // for each row
    $list->setFirst();
    while( $series = $list->getNext() ) {
    
        $seriesArray[ $series->getID() ] = $series->getTitle();
     
    } // next row
    
    
    // Define the Edit link:
    // NOTE: how it ends with "seriesID="
    // it is intened for this link to be concatened with the series_id value in the 
    // above array
    $editLink = 'ex_SeriesEdit.php?seriesID=';


}



//************************************************************************
/** 
 * Process the Data
 *
 * Here we perform the actions of this web page
 */
function processData() 
{
    global $seriesArray;
    global $editLink;

}



//************************************************************************
/** 
 * getHTML()
 *
 * Returns the HTML generated by this page.
 */
function getHTML() 
{
    global $seriesArray;
    global $editLink;
 
    // Now we create a Template object 
    // NOTE: (optional parameter is to set the path to your template file )
    // ex   $template = new Template( "path/to/template/files/here.php" );
    // if you don't set it, it assumes the template is in the same directory
    // as your script.
    //
    $template = new Template( );
    
    // Now we pass/set the values of variables in the Template
    // 1st parameter is the name of the variable as it will be called in the template
    // 2nd parameter is the current variable that you want to pass in
    $template->set( 'seriesList', $seriesArray);
    $template->set( 'editLink', $editLink);
    
    // now we get the HTML of the Template and display that for our page.
    return $template->fetch( 'ex_SeriesList.tpl' );
    
}

?>
