<p class="text">Spiritual Conversation, Staff:  Able to speak about God, spiritual questions, but were not able to share four points of Gospel and explain how someone could pray to receive Christ.  However, if doing a survey and the conversation does not go beyond the content of the survey questions, this would not be a spiritual conversation.  If two staff together, the main 'sharer' should record.  If staff and student, staff should record as "spiritual conversation, staff" regardless of who did most of the sharing.</p>

<p class="text">Spiritual Conversation, Disciple:  Able to speak about God, spiritual questions, but were not able to share four points of Gospel and explain how someone could pray to receive Christ.  However if doing a survey and the conversation does not go beyond the content of the survey questions, this would not be a spiritual conversation.  This would be one student alone or a couple of students together but no staff present.</p>


<p class="text">Gospel Presentation, Staff:  The four points of the Gospel and how someone can pray to receive Christ were clearly presented.  If two staff together, the main 'sharer' should record.  If staff and student, staff should record as "gospel presentation, staff" regardless of who did most of the sharing.</p><p class="text">Gospel Presentation, Disciple:  The four points of the Gospel and how someone can pray to receive Christ were clearly presented.  This would be one student alone or a couple of students together but no staff present.</p><p class="text">Holy Spirit presentation, Staff:  This is a one to one presentation of the ministry of the Holy Spirit, including an opportunity to pray to be filled and an explanation of spiritual breathing.  If staff and student, staff should record as "Holy Spirit presentation, staff" regardless of who did most of the sharing.</p>

<p class="text">Holy Spirit presentation, Disciple:  This is a one to one presentation of the ministry of the Holy Spirit, including an opportunity to pray to be filled and an explanation of spiritual breathing.</p><p class="text">Follow-up, Staff:  Number who completed the basic fourth follow-up lessons this week.</p>

<p class="text">Follow-up, Disciple:  Number who completed the basic fourth follow-up lessons this week.</p>