<?php
/**
 * @package cim_reg
 */ 
/**
 * class obj_RegProcessSideBar
 * <pre> 
 * This object manages the display of the registration process side bar.
 * </pre>
 * @author Hobbe Smit	(mostly taken from obj_AdminSideBar.php by Johnny Hausman)
 * Date:   11 August 2007  (12 April 2005)
 */
class  obj_RegProcessSideBar {

	//CONSTANTS:
	/** The XML root node name for this object */
    const MULTILINGUAL_PAGE_KEY = 'obj_RegProcessSideBar';

	//VARIABLES:
	
	/** @var [STRING] The path to this module's root directory */
	protected $pathModuleRoot;
	
	/** @var [STRING] The path to the site's root directory */
	protected $pathToRoot;
	
	/** @var [OBJECT] the template object */
	protected $template;
	
	/** @var [OBJECT] the labels object */
	protected $labels;
	
	/** @var [ARRAY] array of links for the sidebar */
	protected $links;
	
		/** @var [BOOLEAN] whether registration is completed (show cancel link and not display notice) */
 	protected $reg_completed;

   /** @var [ARRAY] array of admin links for the sidebar */
// 	protected $adminLinks;

   /** @var [ARRAY] array of campus level links for the sidebar */
// 	protected $campusLevelLinks;

	//CLASS CONSTRUCTOR
	//************************************************************************
	/**
	 * function __construct
	 * <pre>
	 * Initialize the obj_AdminSideBar Object.
	 * </pre>
	 * @param $modulePath [STRING] The path from the root directory to this 
	 * module's root directory.
	 * @param $viewer [OBJECT] The viewer object 
	 * @return [void]
	 */
    function __construct( $modulePath, $viewer, $regCompleted = false)	//, $showAllLinks = false ) 
    {
        
        $this->pathModuleRoot = $modulePath;
//        $this->pathToRoot = $rootPath;

// 			$this->show_all_links = $showAllLinks;

		  $this->reg_completed = $regCompleted;

        $this->links = array();
//         $this->adminLinks = array();
//         $this->campusLevelLinks = array();

        // load any labels assigned to this page
        $languageID = $viewer->getLanguageID();
        $seriesKey = modulecim_reg::MULTILINGUAL_SERIES_KEY;
        $pageKey = obj_RegProcessSideBar::MULTILINGUAL_PAGE_KEY;
        $this->labels = new MultilingualManager( $languageID, $seriesKey, $pageKey );

    }



	//CLASS FUNCTIONS:
	//************************************************************************
	/**
	 * function classMethod
	 * <pre>
	 * [classFunction Description]
	 * </pre>
	 * <pre><code>
	 * [Put PseudoCode Here]
	 * </code></pre>
	 * @param $param1 [$param1 type][optional description of $param1]
	 * @param $param2 [$param2 type][optional description of $param2]
	 * @return [returnValue, can be void]
	 */
    function classMethod($param1, $param2)
    {
        // CODE
    }



    //************************************************************************
	/**
	 * function getHTML
	 * <pre>
	 * This method returns the HTML data generated by this object.
	 * </pre>
	 * @return [STRING] HTML Display data.
	 */
    function getHTML()
    {
        // Create a new Template Object
        $this->template = new Template( $this->pathModuleRoot.'templates/' );

        // store the page labels
        $this->template->setXML( 'pageLabels', $this->labels->getLabelXML() );

//         if ($this->show_all_links == true)
//         {
// 	        $displayLinks = $this->links;
//         }
//         else 
//         {
// 	        // display only 1 link
//         }
	        
        // store the links for the sidebar
		$this->template->set( 'links',$this->links );
		
		if ($this->reg_completed == true)
		{
 			$this->template->set( 'regCompleted', true);
		}

       // store the admin links for the sidebar
// 		$this->template->set( 'adminLinks',$this->adminLinks );

      // store the campus level links for the sidebar
// 		$this->template->set( 'campusLevelLinks',$this->campusLevelLinks );

		// return the html from the commong display template
		return $this->template->fetch( 'obj_RegProcessSideBar.tpl.php' );

    }




	//************************************************************************
	/**
	 * function setLinks
	 * <pre>
	 * Stores the values of the links for this sidebar
	 * </pre>
	 * @param $links [ARRAY] Link Values (key=>link, key=>link,...)
	 * @return [void]
	 */
    function setLinks( $links )
    {
        $this->links = $links;
    }
    
//     //************************************************************************
// 	/**
// 	 * function setLinks
// 	 * <pre>
// 	 * Stores the values of the admin links for this sidebar
// 	 * </pre>
// 	 * @param $links [ARRAY] Link Values (key=>link, key=>link,...)
// 	 * @return [void]
// 	 */
//     function setAdminLinks( $links )
//     {
//         $this->adminLinks = $links;
//     }
//     
//     //************************************************************************
// 	/**
// 	 * function setLinks
// 	 * <pre>
// 	 * Stores the values of the admin links for this sidebar
// 	 * </pre>
// 	 * @param $links [ARRAY] Link Values (key=>link, key=>link,...)
// 	 * @return [void]
// 	 */
//     function setCampusLevelLinks( $links )
//     {
//         $this->campusLevelLinks = $links;
//     }


}

?>