<?php
/**
 * @package cim_stats
 */ 
/**
 * class page_StatsHome 
 * <pre> 
 * Home page for the stats module.
 * </pre>
 * @author Russ Martin
 * Date:   10 Jun 2006
 */
 // RAD Tools: Custom Page
class  page_StatsHome extends PageDisplay {

	//CONSTANTS:
    
    /** The Multilingual Page Key for labels on this page */
    const MULTILINGUAL_PAGE_KEY = 'page_StatsHome';
    

	//VARIABLES:
	
	/** @var [OBJECT] The viewer object. */
	protected $viewer;
	
    /** @var [STRING] The path to this module's root directory. */
	protected $pathModuleRoot;
	
	/** @var [ARRAY] all the links accessible to campus stats coordinators. */
	protected $coordinatorLinks;	
	
	/** @var [ARRAY] all the links accessible to campus directors. */
	protected $cdLinks;

	/** @var [ARRAY] all the links accessible to the regional teams. */
	protected $rtLinks;
	
	/** @var [ARRAY] all the links accessible to the national team. */
	protected $ntLinks;
	
	protected $isNational;
	protected $isRegional;
	protected $isCD;
	protected $isStatsCoordinator;
	protected $isAllStaff;


	//CLASS CONSTRUCTOR
	//************************************************************************
	/**
	 * function __construct
	 * <pre>
	 * Initialize the object.
	 * </pre>
	 * @param $pathModuleRoot [STRING] The path to the module's root dir.
	 * @param $viewer [OBJECT] The viewer object.
	 * @return [void]
	 */
    function __construct($pathModuleRoot, $viewer ) 
    {
    
        parent::__construct();
        
        // initialzie the object values
        $this->pathModuleRoot = $pathModuleRoot;
        $this->viewer = $viewer;
        
        // now initialize the labels for this page
        // start by loading the default field labels for this Module
        $languageID = $viewer->getLanguageID();
        $seriesKey = modulecim_stats::MULTILINGUAL_SERIES_KEY;
        $pageKey = page_StatsHome::MULTILINGUAL_PAGE_KEY;
        $this->labels = new MultilingualManager( $languageID, $seriesKey, $pageKey );
        
        $this->isNational = false;
        $this->isRegional = false;
        $this->isCD = false;
        $this->isStatsCoordinator = false;
        $this->isAllStaff = false;

         
    }



	//CLASS FUNCTIONS:
	//************************************************************************
	/**
	 * function classMethod
	 * <pre>
	 * [classFunction Description]
	 * </pre>
	 * <pre><code>
	 * [Put PseudoCode Here]
	 * </code></pre>
	 * @param $param1 [$param1 type][optional description of $param1]
	 * @param $param2 [$param2 type][optional description of $param2]
	 * @return [returnValue, can be void]
	 */
    function classMethod($param1, $param2) 
    {
        // CODE
    }	
    
    
    
    //************************************************************************
	/**
	 * function getHTML
	 * <pre>
	 * This method returns the HTML data generated by this object.
	 * </pre>
	 * @return [STRING] HTML Display data.
	 */
    function getHTML() 
    {

        // Uncomment the following line if you want to create a template 
        // tailored for this page:
        $path = $this->pathModuleRoot.'templates/';
        // Otherwise use the standard Templates for the site:
        //$path = SITE_PATH_TEMPLATES;
        

        /*
         * Update any label tags ...
         */
        // example:
            // $name = $user->getName();
            // $this->labels->setLabelTag( '[Title]', '[userName]', $name);


        // NOTE:  this parent method prepares the $this->template with the 
        // common Display data.  
        $this->prepareTemplate($path);
        
        $this->template->set('coordinatorLinkValues', $this->coordinatorLinks );
        $this->template->set('cdLinkValues', $this->cdLinks );
        $this->template->set('rtLinkValues', $this->rtLinks );
        $this->template->set('ntLinkValues', $this->ntLinks );
        
        $this->template->set('isNational',$this->isNational);
        $this->template->set('isRegional',$this->isRegional);
        $this->template->set('isCD',$this->isCD);
        $this->template->set('isStatsCoordinator',$this->isStatsCoordinator);
        $this->template->set('isAllStaff',$this->isAllStaff);
        
        // uncomment this line if you are creating a template for this page
		$templateName = 'page_StatsHome.php';
		// otherwise use the generic site template
		//$templateName = '';
		
		return $this->template->fetch( $templateName );
        
    }
    
    function setMyLinks( $allStaffLinks, $coordinatorLinks, $cdLinks, $rtLinks, $ntLinks )
    {
        $this->setLinks( $allStaffLinks );
        
        $this->coordinatorLinks = $coordinatorLinks;
        $this->cdLinks = $cdLinks;
        $this->rtLinks = $rtLinks;
        $this->ntLinks = $ntLinks;
        
        return;
    }
    
    function setPerms( $isNational, $isRegional, $isCD, $isStatsCoordinator, $isAllStaff )
    {
        $this->isNational = $isNational;
        $this->isRegional = $isRegional;
        $this->isCD = $isCD;
        $this->isStatsCoordinator = $isStatsCoordinator;
        $this->isAllStaff = $isAllStaff;
        
    }
	
}

?>